In [1]:
import pandas as pd
import numpy as np

In [4]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv"
crime = pd.read_csv(url, sep=",")
crime.head(10)

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
3,1963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
4,1964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800
5,1965,193526000,4739400,387390,4352000,9960,23410,138690,215330,1282500,2572600,496900
6,1966,195576000,5223500,430180,4793300,11040,25820,157990,235330,1410100,2822000,561200
7,1967,197457000,5903400,499930,5403500,12240,27620,202910,257160,1632100,3111600,659800
8,1968,199399000,6720200,595010,6125200,13800,31670,262840,286700,1858900,3482700,783600
9,1969,201385000,7410900,661870,6749000,14760,37170,298850,311090,1981900,3888600,878500

In [5]:
print(type(crime.shape[1]))

<class 'int'>

In [7]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                55 non-null     int64
 1   Population          55 non-null     int64
 2   Total               55 non-null     int64
 3   Violent             55 non-null     int64
 4   Property            55 non-null     int64
 5   Murder              55 non-null     int64
 6   Forcible_Rape       55 non-null     int64
 7   Robbery             55 non-null     int64
 8   Aggravated_assault  55 non-null     int64
 9   Burglary            55 non-null     int64
 10  Larceny_Theft       55 non-null     int64
 11  Vehicle_Theft       55 non-null     int64
dtypes: int64(12)
memory usage: 5.3 KB

In [10]:
# Step 5. Convert the type of the column Year to datetime64

crime['Year'] = pd.to_datetime(crime['Year'], format='%Y', errors='coerce')
print(crime['Year'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 55 entries, 0 to 54
Series name: Year
Non-Null Count  Dtype
--------------  -----
55 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 572.0 bytes
None

In [ ]:
# Step 6. Set the Year column as the index of the dataframe
crime.set_index('Year')

KeyError: "None of ['Year'] are in the columns"

In [16]:
crime.head()

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft,Yera
Year,,,,,,,,,,,,
1960-01-01,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200,1960-01-01
1961-01-01,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000,1961-01-01
1962-01-01,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800,1962-01-01
1963-01-01,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300,1963-01-01
1964-01-01,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800,1964-01-01

In [22]:
# Step 7. Delete the Total column
crime = crime.drop('Total', axis=1)
crime.head()

,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft,Yera
Year,,,,,,,,,,,
1960-01-01,179323175,288460,3095700,9110,17190,107840,154320,912100,1855400,328200,1960-01-01
1961-01-01,182992000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000,1961-01-01
1962-01-01,185771000,301510,3450700,8530,17550,110860,164570,994300,2089600,366800,1962-01-01
1963-01-01,188483000,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300,1963-01-01
1964-01-01,191141000,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800,1964-01-01

In [27]:
# Step 8. Group the year by decades and sum the values
# Pay attention to the Population column number, summing this column is a mistake

crime_decades = crime.resample('10AS').sum(numeric_only=True)
population = crime['Population'].resample('10AS').max()
crime_decades['Population'] = population
crime_decades

/tmp/ipykernel_1298/3606897259.py:4: FutureWarning: 'AS' is deprecated and will be removed in a future version, please use 'YS' instead.
  crime_decades = crime.resample('10AS').sum(numeric_only=True)
/tmp/ipykernel_1298/3606897259.py:5: FutureWarning: 'AS' is deprecated and will be removed in a future version, please use 'YS' instead.
  population = crime['Population'].resample('10AS').max()

,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,
1960-01-01,201385000.0,4134930,45160900,106180,236720,1633510,2158520,13321100,26547700,5292100
1970-01-01,220099000.0,9607930,91383800,192230,554570,4159020,4702120,28486000,53157800,9739900
1980-01-01,248239000.0,14074328,117048900,206439,865639,5383109,7619130,33073494,72040253,11935411
1990-01-01,272690813.0,17527048,119053499,211664,998827,5748930,10568963,26750015,77679366,14624418
2000-01-01,307006550.0,13968056,100944369,163068,922499,4230366,8652124,21565176,67970291,11412834
2010-01-01,318857056.0,6072017,44095950,72867,421059,1749809,3764142,10125170,30401698,3569080

In [29]:
# Step 9. What is the most dangerous decade to live in the US?
MDD = crime_decades['Murder'].idxmax()
print(MDD)

1990-01-01 00:00:00

In [33]:
# 创造一个新指标：犯罪率 = 暴力犯罪总数 / 总人口
crime_decades['Violent_Rate'] = crime_decades['Violent'] / crime_decades['Population']
crime_decades['Violent_Rate'].idxmax()

Timestamp('1990-01-01 00:00:00')

In [35]:
crime_decades.idxmax(0)

Population           2010-01-01
Violent              1990-01-01
Property             1990-01-01
Murder               1990-01-01
Forcible_Rape        1990-01-01
Robbery              1990-01-01
Aggravated_assault   1990-01-01
Burglary             1980-01-01
Larceny_Theft        1990-01-01
Vehicle_Theft        1990-01-01
Voilent_Rate         1990-01-01
Violent_Rate         1990-01-01
dtype: datetime64[ns]