In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv"

baby_names = pd.read_csv(url)
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

In [3]:
new_bn = baby_names.drop(['Unnamed: 0', 'Id'], axis=1)
print(new_bn)

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

In [4]:
# Step 6. What year has the highest number of baby names in the dataset?
new_bn['Year'].value_counts().idxmax()

2008

In [5]:
highest_number = new_bn.groupby('Year')['Count'].sum().idxmax()
highest_number

2007

In [11]:
# Step 7. Is there more male or female names in the dataset?
genders_count = new_bn.groupby('Gender')['Count'].sum()
genders_count

Gender
F    16380293
M    19041199
Name: Count, dtype: int64

In [ ]:
genders_count = new_bn['Gender'].value_counts()
genders_count

Gender
F    558846
M    457549
Name: count, dtype: int64

In [21]:
# Step 8. Group the dataset by name and assign to names
names = new_bn.groupby('Name').sum()

names = names.drop(['Year', 'Gender', 'State'], axis = 1)

names.sort_values('Count', ascending=False)

             Count
Name
Jacob       242874
Emma        214852
Michael     214405
Ethan       209277
Isabella    204798
...            ...
Eniola           5
Atlantis         5
Marci            5
Simarpreet       5
Nita             5

[17632 rows x 1 columns]

In [16]:
# Step 9. How many different names exist in the dataset?
names.shape[0]

17632

In [25]:
# Step 10. What is the name with most occurrences?
names.Count.idxmax()

'Jacob'

In [38]:
# Step 11. How many different names have the least occurrences?
mini_count = names['Count'].min()
least_names = names.loc[names['Count'] == mini_count]
print(least_names.sample)

<bound method NDFrame.sample of           Count
Name
Aadarsh       5
Aadin         5
Aaima         5
Aalaya        5
Aaminah       5
...         ...
Zyien         5
Zyire         5
Zykeriah      5
Zykierra      5
Zymari        5

[2578 rows x 1 columns]>

In [44]:
# Step 12. What is the median name occurrence?
sort = names.Count.median()
median_name = names.loc[names['Count'] == sort]
median_name

         Count
Name
Aishani     49
Alara       49
Alysse      49
Ameir       49
Anely       49
...        ...
Sriram      49
Trinton     49
Vita        49
Yoni        49
Zuleima     49

[66 rows x 1 columns]

In [45]:
# Step 13. What is the standard deviation of names?
names.describe()

               Count
count   17632.000000
mean     2008.932169
std     11006.069468
min         5.000000
25%        11.000000
50%        49.000000
75%       337.000000
max    242874.000000

In [46]:
names.Count.std()

11006.069467891111